-- ====================================================================
-- 1. CLEAN UP EXHAUSTIVELY (Fresh start guarantee)
-- ====================================================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.likes CASCADE; -- Dropped as requested
DROP TABLE IF EXISTS public.gratitude_journal CASCADE; -- Dropped as requested
DROP TABLE IF EXISTS public.friends CASCADE; 
DROP TABLE IF EXISTS public.friendships CASCADE; -- Updated to match your React Native code
DROP TABLE IF EXISTS public.posts CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ====================================================================
-- 2. CREATE TABLES
-- ====================================================================

-- User Profiles (Linked directly to Supabase Auth)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,         -- Added to match ProfileTab.js
  avatar_url TEXT,           -- Added to match ProfileTab.js
  email TEXT
);

-- Friendships System (Updated to match frontend sendFriendRequest logic)
CREATE TABLE public.friendships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(sender_id, receiver_id)
);

-- Daily Completed Tasks (Consolidated Post Table)
CREATE TABLE public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  task_title TEXT NOT NULL,          -- e.g., "Climbed a tree"
  media_url TEXT,                    -- URL link to Storage
  media_type TEXT DEFAULT 'photo',   -- 'photo' or 'video' based on your CameraCapture.js
  liked_by_users UUID[] DEFAULT '{}',-- Array of user IDs who liked it (Replaces the Likes table)
  comments JSONB DEFAULT '[]'::jsonb,-- JSON array storing comment objects [{user: 'x', text: 'y'}]
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ====================================================================
-- 3. CREATE AUTOMATIC SIGNUP TRIGGER
-- ====================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username)
  VALUES (
    new.id,
    new.email,
    -- Pulls custom username dynamically from your mobile app signup form data option
    coalesce(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8))
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ====================================================================
-- 4. ENABLE TABLES FOR PUBLIC VISIBILITY (Turns off RLS locks for testing)
-- ====================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow everything to authenticated users" ON public.profiles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow everything to authenticated users" ON public.friendships FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow everything to authenticated users" ON public.posts FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ====================================================================
-- 5. STORAGE BUCKETS AND STORAGE RLS POLICIES
-- ====================================================================

-- Ensure the 'post-media' bucket exists and is set to public
INSERT INTO storage.buckets (id, name, public) 
VALUES ('post-media', 'post-media', true)
ON CONFLICT (id) DO NOTHING;

-- Ensure the 'avatars' bucket exists and is set to public
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated uploads to post-media
CREATE POLICY "Allow authenticated uploads to post-media"
ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'post-media');

-- Allow public read access to post-media
CREATE POLICY "Allow public read access to post-media"
ON storage.objects FOR SELECT TO public USING (bucket_id = 'post-media');

-- Allow users to update their own files in post-media
CREATE POLICY "Allow users to update their own files in post-media"
ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'post-media' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Allow users to delete their own files in post-media
CREATE POLICY "Allow users to delete their own files in post-media"
ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'post-media' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Allow authenticated uploads to avatars
CREATE POLICY "Allow authenticated uploads to avatars"
ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'avatars');

-- Allow public read access to avatars
CREATE POLICY "Allow public read access to avatars"
ON storage.objects FOR SELECT TO public USING (bucket_id = 'avatars');

-- Allow users to update their own files in avatars
CREATE POLICY "Allow users to update their own files in avatars"
ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);

-- Allow users to delete their own files in avatars
CREATE POLICY "Allow users to delete their own files in avatars"
ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);
